### ISSUE TITLE
Would you be interested in a FTMS_gatt_server as an example?

### ISSUE THREAD

**Issue by WouterJD** [kevincar/bless#74]
**Describe the solution you'd like**
Gatt_server.py is a good start to create a server and I managed to create an FitnessMachineServer.

**Describe alternatives you've considered**
If you like, I can create a sample code (removing all application dedicated stuff) for reference.

**Additional context**
This example can be added to the examples

**Comment by kevincar** [comment]
Possibly. Can you describe the purpose it would serve?

**Comment by kevincar** [comment]
Sounds good. Make a pull request on the issue.

**Comment by kevincar** [comment]
See [here](https://github.com/kevincar/bless/pull/77#issuecomment-1142577057)

**Comment by WouterJD** [comment]
Hi Kevin

 

I know that this issue is closed.

 

My question is when you finalize your development and merge into master, so that I can use the master branch as a reference.

Thanks, Wouter

 

 

Van: Kevin Davis ***@***.***> 
Verzonden: dinsdag 31 mei 2022 21:49
Aan: kevincar/bless ***@***.***>
CC: Wouter Dubbeldam ***@***.***>; Author ***@***.***>
Onderwerp: Re: [kevincar/bless] Would you be interested in a FTMS_gatt_server as an example? (Issue #74)

 

See here <https://github.com/kevincar/bless/pull/77#issuecomment-1142577057>

**Comment by kevincar** [comment]
Merge and version update should happen in the next couple days. Just wanted to get some of the other issues out of the way.

**Comment by WouterJD** [comment]
👍Please keep me posted

**Comment by kevincar** [comment]
@WouterJD

[New version](https://github.com/kevincar/bless/releases/tag/v0.2.4) is released

**Comment by WouterJD** [comment]
Thanks, I published BLE/bless version - using your published version.

**Comment by WouterJD** [comment]
👍Met vriendelijke groetWouter Dubbeldam -------- Oorspronkelijk bericht --------Van: Kevin Davis ***@***.***>Datum: wo 8 jun. 2022 16:11Aan: kevincar/bless ***@***.***>Cc: Wouter Dubbeldam ***@***.***>, Mention ***@***.***>Onderwerp: Re: [kevincar/bless] Would you be interested in a FTMS_gatt_server as an example? (Issue #74)
@WouterJD
New version is released
