### ISSUE TITLE
Errors running examples

### ISSUE THREAD

**Issue by Regjoz** [kevincar/bless#80]
**The problem**
With python 3.10.4 working inside a virtual-env, bless in branch develop and executing both examples. 

I get the error:

unexpected error processing a message: interface "org.bluez.LEAdvertisement1"  does not have property "TxPower" 

Any of the examples works, it keep frozen with the message:

Write 0xF to the advertised characteristics. 

I send the message 0xF using the application LightBlue  (available in play store) and the python example doesn't work. I also receive a notification in the Android app:
 "Failed to write characteristics Status 1"

The examples also use the computer name instead the one defined in the example. 

**Reproduction**
Install bless develop branch in a virtual-env and run any of the examples. 

**Expected behavior**
Any error message on terminal and sending F will finish the program with a log trace. 

**Desktop**
 - OS: Ubuntu 22.04 LTS

**Comment by kevincar** [comment]
@Regjoz Thanks for posting this. #85 should fix it. Reopen if it you find it doesn't.

@Jakeler Thanks for the fix
