### ISSUE TITLE
Adapter selection

### ISSUE THREAD

**Issue by Jakeler** [kevincar/bless#86]
**Describe the solution you'd like**
If there are multiple BLE adapters on the host it should be possible to specify which one is used for the server. Currently it picks just the first it finds on dbus: https://github.com/kevincar/bless/blob/v0.2.4/bless/backends/bluezdbus/dbus/utils.py#L33

I would keep the API similar to bleak, like `BleakClient(adapter="hci1")` or `BleakScanner(adapter="hci1")` it could be `BlessServer(adapter="hci1")`.

**Describe alternatives you've considered**
Instead of just receiving a string, bless could offer a `list_adapters()` function. That would allow to get and pass objects with more data, for example the full bluez path, but I am not sure if this is really needed or helpful. 
In any case such a function could be useful for users to find out adapter names.

**Additional context**
Seems to only be relevant for Linux (including Android on bleak). 
More info about how this is handled on Mac or Windows is appreciated.

**Comment by kevincar** [comment]
Apologies for the delay. Linux implementation was a quick fix. Implemented a [`list_adapters()`](https://github.com/kevincar/bless/blob/1221a16e11d093dce0d40e6d6685794f7e21726b/bless/backends/bluezdbus/dbus/utils.py#L9) function as suggested.

As mentioned, the macOS and Windows implementations seem to be more involved. macOS previously provided a developer app called Bluetooth Explorer that allowed users to select the primary HCI adapter to use. With updates to BigSur and Monterey, this is no longer seems possible.

For Windows, there are UWP [`BluetoothAdaptor`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjO8abVkaD7AhVfUDABHWi7AHQQFnoECBAQAQ&url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fuwp%2Fapi%2Fwindows.devices.bluetooth.bluetoothadapter&usg=AOvVaw1Tk9TQsDiPey_0zzf7XmC9) classes that represent BLE adapters but currently there is not a clear way to dictate which adapter supplies the [`GattServiceProvider`](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovider.createasync?view=winrt-22621#windows-devices-bluetooth-genericattributeprofile-gattserviceprovider-createasync(system-guid)) for building the Gatt tree.

One approach I've started diving into is building compiled binaries that utilize the `GattServiceProvider` for windows and the `CBPeripheralManager` on macOS and running debuggers to pinpoint how the underlying API access and select the internal BLE adapters, but this is proving to take a bit more time than I have available for this issue at the moment.

Will merge updates to develop soon.
